getwd()
setwd("your/file/path")

install.packages("rtweet")
install.packages("data.table")

library(rtweet) 
library(data.table)

cnn_tweets <- get_timeline("@cnn", n=3000)
fox_tweets <- get_timeline("@FoxNews", n=3000)
theatlantic_tweets <- get_timeline("@TheAtlantic", n=3000)
MSNBC_tweets <- get_timeline("@MSNBC", n=3000)
Breitbart_tweets <- get_timeline("@BreitbartNews", n=3000)
WSJ_tweets <- get_timeline("@WSJ", n=3000)
nytimes_tweets <- get_timeline("@nytimes", n=3000)
theeconomist_tweets <- get_timeline("@TheEconomist", n=3000)
bloomberg_tweets <- get_timeline("@business", n=3000)
washingtonpost_tweets <- get_timeline("@washingtonpost", n=3000)

fwrite(cnn_tweets, file="cnntweets.csv")
fwrite(fox_tweets, file="foxtweets.csv")
fwrite(theatlantic_tweets, file="atlantictweets.csv")
fwrite(MSNBC_tweets, file="msnbctweets.csv")
fwrite(Breitbart_tweets, file="breitbarttweets.csv")
fwrite(WSJ_tweets, file="wsjtweets.csv")
fwrite(nytimes_tweets, file="nyttweets.csv")
fwrite(theeconomist_tweets, file="economisttweets.csv")
fwrite(bloomberg_tweets, file="bloombergtweets.csv")
fwrite(washingtonpost_tweets, file="washingtonposttweets.csv")
